{
  "metadata": {
    "generated_at": "2025-11-12T11:23:22.307451+00:00",
    "generator": "static_tf_config_build.sh",
    "translation_units": "m",
    "rotation_units": "deg",
    "rotation_order": {
      "world_axes": [
        "X",
        "Y",
        "Z"
      ],
      "body_axes": [
        "X",
        "Y",
        "Z"
      ]
    },
    "urdf_source": "/home/jetson/L2/src/tf_tools/../description/urdf/yam.urdf"
  },
  "tf_tree": [
    {
      "parent": "world",
      "child": "base_link"
    },
    {
      "parent": "world",
      "child": "camera_link"
    }
  ],
  "transforms": {
    "world_to_base_link": {
      "name": "world_to_base_link",
      "parent_frame": "world",
      "child_frame": "base_link",
      "translation_m": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "rotation_deg": {
        "about_world_axes": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        },
        "about_body_axes": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0
        }
      },
      "transform_sequence": [
        {
          "type": "world_axis",
          "axis": "X",
          "angle_deg": 0.0
        },
        {
          "type": "world_axis",
          "axis": "Y",
          "angle_deg": 0.0
        },
        {
          "type": "world_axis",
          "axis": "Z",
          "angle_deg": 0.0
        },
        {
          "type": "body_axis",
          "axis": "X",
          "angle_deg": 0.0
        },
        {
          "type": "body_axis",
          "axis": "Y",
          "angle_deg": 0.0
        },
        {
          "type": "body_axis",
          "axis": "Z",
          "angle_deg": 0.0
        }
      ],
      "quaternion": {
        "forward_parent_to_child": {
          "x": 0.0,
          "y": 0.0,
          "z": 0.0,
          "w": 1.0
        },
        "inverse_child_to_parent": {
          "x": -0.0,
          "y": -0.0,
          "z": -0.0,
          "w": 1.0
        }
      },
      "inverse_translation_m": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      }
    },
    "world_to_camera_link": {
      "name": "world_to_camera_link",
      "parent_frame": "world",
      "child_frame": "camera_link",
      "translation_m": {
        "x": 0.5,
        "y": 0.2,
        "z": 0.8
      },
      "rotation_deg": {
        "about_world_axes": {
          "x": 10.0,
          "y": 0.0,
          "z": 0.0
        },
        "about_body_axes": {
          "x": 0.0,
          "y": 5.0,
          "z": 0.0
        }
      },
      "transform_sequence": [
        {
          "type": "world_axis",
          "axis": "X",
          "angle_deg": 10.0
        },
        {
          "type": "world_axis",
          "axis": "Y",
          "angle_deg": 0.0
        },
        {
          "type": "world_axis",
          "axis": "Z",
          "angle_deg": 0.0
        },
        {
          "type": "body_axis",
          "axis": "X",
          "angle_deg": 0.0
        },
        {
          "type": "body_axis",
          "axis": "Y",
          "angle_deg": 5.0
        },
        {
          "type": "body_axis",
          "axis": "Z",
          "angle_deg": 0.0
        }
      ],
      "quaternion": {
        "forward_parent_to_child": {
          "x": 0.0870727897926938,
          "y": 0.04345340242735779,
          "z": 0.0038016801040236755,
          "w": 0.9952465414778341
        },
        "inverse_child_to_parent": {
          "x": -0.0870727897926938,
          "y": -0.04345340242735779,
          "z": -0.0038016801040236755,
          "w": 0.9952465414778341
        }
      },
      "inverse_translation_m": {
        "x": -0.43245891528419544,
        "y": -0.3358800927359859,
        "z": -0.7938286023411368
      }
    }
  },
  "urdf_chain": {
    "source_file": "/home/jetson/L2/src/tf_tools/../description/urdf/yam.urdf",
    "links": [
      {
        "joint": "joint6",
        "parent": "link_5",
        "child": "link_6",
        "origin_xyz": {
          "x": -4.0742e-16,
          "y": 0.0353,
          "z": 0.0395
        },
        "origin_rpy": {
          "roll": -1.5708,
          "pitch": 3.81639e-16,
          "yaw": 4.68582e-15
        }
      },
      {
        "joint": "joint5",
        "parent": "link_4",
        "child": "link_5",
        "origin_xyz": {
          "x": -0.0739968,
          "y": -0.0395003,
          "z": 2.44738e-05
        },
        "origin_rpy": {
          "roll": -1.5708,
          "pitch": 1.5708,
          "yaw": 0.0
        }
      },
      {
        "joint": "joint4",
        "parent": "link_3",
        "child": "link_4",
        "origin_xyz": {
          "x": -0.245,
          "y": -0.0600003,
          "z": -1.9984e-15
        },
        "origin_rpy": {
          "roll": -5.65471e-31,
          "pitch": -1.1507e-13,
          "yaw": 2.94252e-43
        }
      },
      {
        "joint": "joint3",
        "parent": "link_2",
        "child": "link_3",
        "origin_xyz": {
          "x": 0.264,
          "y": 0.0,
          "z": 6.77626e-21
        },
        "origin_rpy": {
          "roll": -3.14159,
          "pitch": 1.26218e-29,
          "yaw": 7.88861e-31
        }
      },
      {
        "joint": "joint2",
        "parent": "link_1",
        "child": "link_2",
        "origin_xyz": {
          "x": 2.5e-05,
          "y": -0.02,
          "z": 0.0409
        },
        "origin_rpy": {
          "roll": 1.5708,
          "pitch": -1.98004e-28,
          "yaw": 1.5708
        }
      },
      {
        "joint": "joint1",
        "parent": "base_link",
        "child": "link_1",
        "origin_xyz": {
          "x": -3.55271e-18,
          "y": -1.05495e-18,
          "z": 0.0631
        },
        "origin_rpy": {
          "roll": 0.0,
          "pitch": -0.0,
          "yaw": 1.5708
        }
      }
    ]
  }
}
